#!/usr/bin/env php
<?php
function exception_error_handler($severity, $message, $file, $line) {
    throw new ErrorException($message, 0, $severity, $file, $line);
}
set_error_handler("exception_error_handler");

require __DIR__ . '/vendor/autoload.php';

use GeoIPServer\Console\StartServer;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;
use Illuminate\Console\Application;

$container = new Container;
$events = new Dispatcher($container);

$artisan = new Application($container, $events, 'GeoIP Server');
$artisan->setName('GeoIP Server');

$artisan->resolve(StartServer::class);

$artisan->run();
